name: eden-license

on:
  pull_request_target:
    branches: [ master ]

jobs:
  license-header:
    runs-on: source
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch
        run: git fetch origin

        # TODO: fix the script
      - name: Make script executable
        run: chmod +x ./.ci/license-header.rb

      - name: Check license headers
        run: ./.ci/license-header.rb
